server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  task:
    execution:
      pool:
        core-size: 10
        max-size: 50
        queue-capacity: 10000
        keep-alive: 10s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blas
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 465
    username: blasvietnam@gmail.com
    password: pdaifcxvnvsqyums
#    username: blassystemvietnam@gmail.com
#    password: gcfeqaxvdfafgxoc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.3
            checkserveridentity: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
blas:
  aliasBlasPrivateKey: blasSecretKey
  certificate: BlasSecretKey.p12
  service:
    serviceName: blas-email
  gate-interceptor:
    enableLogRequest: true
    enableLogLocalRequest: false
  blas-service-support:
    throughServiceSupport: true
    endpointCheckMaintenance: http://localhost:8084/maintenance/check
  blas-email:
    dailyQuotaNormalUser: 10
    numberTryToSendEmailAgain: 9
    waitTimeFirstTryToSendEmailAgain: 1000 #miliseconds
    needMaskFields: password
  blas-idp:
    isSendEmailAlert: false
    jwt:
      timeToExpiredInternalToken: 120 #2 minutes
#logging:
#  file:
#    name: application.log
#  level:
#    root: DEBUG
#    org.springframework: DEBUG
#    com.blas.blasemail: DEBUG
