server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blas
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'
email:
  emailSender: blascoffeevn@gmail.com
  password: tuajjksryooovuoa
  portSender: 465
#logging:
#  file:
#    name: application.log
#  level:
#    root: DEBUG
#    org.springframework: WARN
#    com.example.TaskManagement.service: DEBUG