server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blas
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  mail:
    host: smtp.gmail.com
    port: 465
    username: blasvietnam@gmail.com
    password: pdaifcxvnvsqyums
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.2
            checkserveridentity: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
blas:
  blas-email:
    dailyQuotaNormalUser: 10
    numberTryToSendEmailAgain: 4
    waitTimeFirstTryToSendEmailAgain: 1000 #miliseconds
    needMaskFields: password
  blas-idp:
    isSendEmailAlert: true
    jwt:
      secret: ZPYu33tz8QYU3hwJQXgHpZsKfYn0r2poopBx7x1n3rmeIvuGU4wf65kk6rV1DrN
#logging:
#  file:
#    name: application.log
#  level:
#    root: DEBUG
#    org.springframework: WARN
#    com.example.TaskManagement.service: DEBUG
