server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blas
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'
blas:
  blas-idp:
    isSendEmailAlert: true
    jwt:
      secret: ZPYu33tz8QYU3hwJQXgHpZsKfYn0r2poopBx7x1n3rmeIvuGU4wf65kk6rV1DrN
      timeToExpired: 8640000 #100 days
  blas-email:
    emailSender: blasvietnam@gmail.com
    password: pdaifcxvnvsqyums
    portSender: 465
#logging:
#  file:
#    name: application.log
#  level:
#    root: DEBUG
#    org.springframework: WARN
#    com.example.TaskManagement.service: DEBUG
