server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
spring:
  profiles:
    active: local
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 1000000
        keep-alive: 5s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql-url-local}
    username: ${mysql-username}
    password: ${mysql-password}
  data:
    mongodb:
      uri: ${mongodb-url}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
  main:
    allow-bean-definition-overriding: true
blas:
  aliasBlasPrivateKey: blasSecretKey
  certificate: BlasSecretKey.p12
  service:
    serviceName: blas-notification
  blas-service-support:
    throughServiceSupport: true
    endpointCheckMaintenance: http://localhost:8084/maintenance/check
  blas-notification:
    mail:
      host: smtp.gmail.com
      port: 465
      credentials: ${mail-credentials}
    dailyQuotaNormalUser: 10
    numberTryToSendEmailAgain: 9
    waitTimeFirstTryToSendEmailAgain: 1000 #miliseconds
    needMaskFields: password,authenKey
  blas-idp:
    isSendEmailAlert: true
  hazelcast:
    aksNamespace: dev
    hazelcastService: hazelcast

logging:
  level:
    root: INFO
    com.blas: INFO
    org.hibernate: WARN
    com.azure: WARN
    io.micrometer: WARN
    com.hazelcast: ERROR
    org.mongodb: WARN
    org.springframework: WARN
    org.apache.http: WARN
